In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("movies.csv")
df

,index,genres,title
0,0,Action Adventure Fantasy Science Fiction,Avatar
1,1,Adventure Fantasy Action,Pirates of the Caribbean: At World's End
2,2,Action Adventure Crime,Spectre
3,3,Action Crime Drama Thriller,The Dark Knight Rises
4,4,Action Adventure Science Fiction,John Carter
...,...,...,...
4688,4688,Foreign Thriller,Cavite
4689,4689,Action Crime Thriller,El Mariachi
4690,4690,Comedy Romance,Newlyweds
4691,4691,Comedy Drama Romance TV Movie,"Signed, Sealed, Delivered"
4692,4692,Documentary,My Date with Drew

In [3]:
df.shape

(4693, 3)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4693 entries, 0 to 4692
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   index   4693 non-null   int64
 1   genres  4666 non-null   object
 2   title   4693 non-null   object
dtypes: int64(1), object(2)
memory usage: 110.1+ KB

In [5]:
df.describe()

             index
count  4693.000000
mean   2346.000000
std    1354.896737
min       0.000000
25%    1173.000000
50%    2346.000000
75%    3519.000000
max    4692.000000

In [6]:
df.isnull().sum()

index      0
genres    27
title      0
dtype: int64

In [7]:
df["genres"] = df["genres"].fillna('')   #--> replacing the null values with null string

In [8]:
# TF-IDF Vectorization :  It will covert the text words into the numerical formate by creating vector(matrix) for senteces.
                        # It will give the importance value of each word from sentence in matrix formate(means it will give check how many times a word is there in sentence for each unique word and depending on that it will consider the importnace of that word.)

from sklearn.feature_extraction.text import TfidfVectorizer
tfidfv = TfidfVectorizer()
feature_vectors = tfidfv.fit_transform(df["genres"])
print(feature_vectors)

  (0, 9)	0.4707458516730511
  (0, 17)	0.4707458516730511
  (0, 8)	0.5071491125814311
  (0, 1)	0.4130006715194316
  (0, 0)	0.3592031586687302
  (1, 8)	0.6796531732320795
  (1, 1)	0.5534806430329519
  (1, 0)	0.48138419365761775
  (2, 4)	0.6185214118995771
  (2, 1)	0.5928935478061559
  (2, 0)	0.5156631691245587
  (3, 18)	0.48649581688790344
  (3, 6)	0.3629530982869474
  (3, 4)	0.6104131981773028
  (3, 0)	0.5089033268563236
  (4, 9)	0.5461986458318269
  (4, 17)	0.5461986458318269
  (4, 1)	0.47919786591815133
  (4, 0)	0.4167774992516349
  (5, 8)	0.6796531732320795
  (5, 1)	0.5534806430329519
  (5, 0)	0.48138419365761775
  (6, 7)	0.6244061832929827
  (6, 2)	0.7810998132540361
  (7, 9)	0.5461986458318269
  :	:
  (4681, 4)	0.6102991975788721
  (4682, 6)	1.0
  (4683, 12)	1.0
  (4684, 6)	1.0
  (4685, 12)	0.7225522352219937
  (4685, 3)	0.4518041679821976
  (4685, 18)	0.5232506676246239
  (4686, 6)	1.0
  (4687, 18)	0.4337475650346395
  (4687, 6)	0.32359995119961343
  (4687, 9)	0.5946200977977993
  (4687, 17)	0.5946200977977993
  (4688, 10)	0.9317090041908928
  (4688, 18)	0.36320563254114735
  (4689, 18)	0.5220991075145031
  (4689, 4)	0.6550851516506998
  (4689, 0)	0.5461464693828377
  (4690, 16)	0.798923570958297
  (4690, 3)	0.6014325629422163
  (4691, 13)	0.6635938580636817
  (4691, 19)	0.6635938580636817
  (4691, 16)	0.24484495095426653
  (4691, 3)	0.18432016744637073
  (4691, 6)	0.15925893678240202
  (4692, 5)	1.0

#### Cosine Similarity :

In [9]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(feature_vectors)
print(similarity)

[[1.         0.7461881  0.43009327 ... 0.         0.         0.        ]
 [0.7461881  1.         0.5763872  ... 0.         0.         0.        ]
 [0.43009327 0.5763872  1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.30646855 0.        ]
 [0.         0.         0.         ... 0.30646855 1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]

In [10]:
similarity.shape

(4693, 4693)

In [11]:
list_of_all_titles = df['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lantern', 'Toy Story 3', 'Terminator Salvation', 'Furious 7', 'World War Z', 'X-Men: Days of Future Past', 'Star Trek Into Darkness', 'Jack the Giant Slayer', 'The Great Gatsby', 'Prince of Persia: The Sands of Time', 'Pacific Rim', 'Transformers: Dark of the Moon', 'Indiana Jones and the Kingdom of the Crystal Skull', 'The Good Dinosaur', 'Brave', 'Star Trek Beyond', 'WALL·E', 'Rush Hour 3', 'A Christmas Carol', 'Jupiter Ascending', 'The Legend of Tarzan', 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', 'X-Men: Apocalypse', 'The Dark Knight', 'Up', 'Monsters vs Aliens', 'Iron Man', 'Hugo', 'Wild Wild West', 'The Mummy: Tomb of the Dragon Emperor', 'Suicide Squad', 'Evan Almighty', 'Edge of Tomorrow', 'Waterworld', 'G.I. Joe: The Rise of Cobra', 'Inside Out', 'The Jungle Book', 'Iron Man 2', 'Snow White and the Huntsman', 'Maleficent', 'Dawn of the Planet of the Apes', 'The Lovers', '47 Ronin', 'Captain America: The Winter Soldier', 'Shrek Forever After', 'Tomorrowland', 'Big Hero 6', 'Wreck-It Ralph', 'The Polar Express', 'Independence Day: Resurgence', 'How to Train Your Dragon', 'Terminator 3: Rise of the Machines', 'Guardians of the Galaxy', 'Interstellar', 'Inception', 'The Hobbit: An Unexpected Journey', 'The Fast and the Furious', 'The Curious Case of Benjamin Button', 'X-Men: First Class', 'The Hunger Games: Mockingjay - Part 2', "The Sorcerer's Apprentice", 'Poseidon', 'Alice Through the Looking Glass', 'Shrek the Third', 'Warcraft', 'Terminator Genisys', 'The Chronicles of Narnia: The Voyage of the Dawn Treader', 'Pearl Harbor', 'Transformers', 'Alexander', 'Harry Potter and the Order of the Phoenix', 'Harry Potter and the Goblet of Fire', 'Hancock', 'I Am Legend', 'Charlie and the Chocolate Factory', 'Ratatouille', 'Batman Begins', 'Madagascar: Escape 2 Africa', 'Night at the Museum: Battle of the Smithsonian', 'X-Men Origins: Wolverine', 'The Matrix Revolutions', 'Frozen', 'The Matrix Reloaded', 'Thor: The Dark World', 'Mad Max: Fury Road', 'Angels & Demons', 'Thor', 'Bolt', 'G-Force', 'Wrath of the Titans', 'Dark Shadows', 'Mission: Impossible - Rogue Nation', 'The Wolfman', 'Bee Movie', 'Kung Fu Panda 2', 'The Last Airbender', 'Mission: Impossible III', 'White House Down', 'Mars Needs Moms', 'Flushed Away', 'Pan', 'Mr. Peabody & Sherman', 'Troy', "Madagascar 3: Europe's Most Wanted", 'Die Another Day', 'Ghostbusters', 'Armageddon', 'Men in Black II', 'Beowulf', 'Kung Fu Panda 3', 'Mission: Impossible - Ghost Protocol', 'Rise of the Guardians', 'Fun with Dick and Jane', 'The Last Samurai', 'Exodus: Gods and Kings', 'Star Trek', 'Spider-Man', 'How to Train Your Dragon 2', 'Gods of Egypt', 'Stealth', 'Watchmen', 'Lethal Weapon 4', 'Hulk', 'G.I. Joe: Retaliation', 'Sahara', 'Final Fantasy: The Spirits Within', 'Captain America: The First Avenger', 'The World Is Not Enough', 'Master and Commander: The Far Side of the World', 'The Twilight Saga: Breaking Dawn - Part 2', 'Happy Feet Two', 'The Incredible Hulk', 'The BFG', 'The Revenant', 'Turbo', 'Rango', 'Penguins of Madagascar', 'The Bourne Ultimatum', 'Kung Fu Panda', 'Ant-Man', 'The Hunger Games: Catching Fire', 'Home', 'War of the Worlds', 'Bad Boys II', 'Puss in Boots', 'Salt', 'Noah', 'The Adventures of Tintin', 'Harry Potter and the Prisoner of Azkaban', 'Australia', 'After Earth', 'Dinosaur', 'Night at the Museum: Secret of the Tomb', 'Megamind', "Harry Potter and the Philosopher's Stone", 'R.I.P.D.', 'Pirates of the Caribbean: The Curse of the Black Pearl', 'The Hunger Games: Mockingjay - Part 1', 'The Da Vinci Code', 'Rio 2', 'X2', 'Fast Five', 'Sherlock Holmes: A Game of Shadows', 'Clash of the Titans', 'Total Recall', 'The 13th Warrior', 'The Bourne Legacy', 'Batman & Robin', 'How the Grinch Stole Christmas', 'The Day After Tomorrow', 'Mission: Impossible II', 'The Perfect Storm', '4: Rise of the Silver Surfer', 'Life of Pi', 'Ghost Rider', 'Jason Bourne', "Charlie's Angels: Full Throttle", 'Prometheus', 'Stuart Little 2', 'Elysium', 'The Chronicles of Riddick', 'RoboCop', 'Speed Racer', 'How Do You Know', 'Knight and Day', 'Oblivion', 'Star Wars: Episode III - Revenge of the Sith', 'Star Wars: Episode II - Attack of the Clones', 'Monsters, Inc.', 'The Wolverine', 'Star Wars: Episode I - The Phantom Menace', 'The Croods', 'Windtalkers', "The Huntsman: Winter's War", 'Teenage Mutant Ninja Turtles', 'Gravity', "Dante's Peak", 'Teenage Mutant Ninja Turtles: Out of the Shadows', 'Fantastic Four', 'Night at the Museum', 'San Andreas', 'Tomorrow Never Dies', 'The Patriot', "Ocean's Twelve", 'Mr. & Mrs. Smith', 'Insurgent', 'The Aviator', "Gulliver's Travels", 'The Green Hornet', '300: Rise of an Empire', 'The Smurfs', 'Home on the Range', 'Allegiant', 'Real Steel', 'The Smurfs 2', 'Speed 2: Cruise Control', "Ender's Game", 'Live Free or Die Hard', 'The Lord of the Rings: The Fellowship of the Ring', 'Around the World in 80 Days', 'Ali', 'The Cat in the Hat', 'I, Robot', 'Kingdom of Heaven', 'Stuart Little', 'The Princess and the Frog', 'The Martian', 'The Island', 'Town & Country', 'Gone in Sixty Seconds', 'Gladiator', 'Minority Report', 'Harry Potter and the Chamber of Secrets', 'Casino Royale', 'Planet of the Apes', 'Terminator 2: Judgment Day', 'Public Enemies', 'American Gangster', 'True Lies', 'The Taking of Pelham 1 2 3', 'Little Fockers', 'The Other Guys', 'Eraser', 'Django Unchained', 'The Hunchback of Notre Dame', "The Emperor's New Groove", 'The Expendables 2', 'National Treasure', 'Eragon', 'Where the Wild Things Are', 'Epic', 'The Tourist', 'End of Days', 'Blood Diamond', 'The Wolf of Wall Street', 'Batman Forever', 'Starship Troopers', 'Cloud Atlas', "Legend of the Guardians: The Owls of Ga'Hoole", 'Catwoman', 'Hercules', 'Treasure Planet', 'Land of the Lost', 'The Expendables 3', 'Point Break', 'Son of the Mask', 'In the Heart of the Sea', 'The Adventures of Pluto Nash', 'Green Zone', 'The Peanuts Movie', 'The Spanish Prisoner', 'The Mummy Returns', 'Gangs of New York', "Surf's Up", 'The Stepford Wives', 'Black Hawk Down', 'The Campaign', 'The Fifth Element', 'Sex and the City 2', 'The Road to El Dorado', 'Ice Age: Continental Drift', 'Cinderella', 'The Lovely Bones', 'Finding Nemo', 'The Lord of the Rings: The Return of the King', 'The Lord of the Rings: The Two Towers', 'Seventh Son', 'Lara Croft: Tomb Raider', 'Transcendence', 'Jurassic Park III', 'Rise of the Planet of the Apes', 'The Spiderwick Chronicles', 'A Good Day to Die Hard', 'The Alamo', 'The Incredibles', 'Cutthroat Island', 'Percy Jackson & the Olympians: The Lightning Thief', 'Men in Black', 'Toy Story 2', 'Unstoppable', 'Rush Hour 2', 'What Lies Beneath', 'Cloudy with a Chance of Meatballs', 'Ice Age: Dawn of the Dinosaurs', 'The Secret Life of Walter Mitty', "Charlie's Angels", 'The Departed', 'Mulan', 'Tropic Thunder', 'The Girl with the Dragon Tattoo', 'Die Hard: With a Vengeance', 'Sherlock Holmes', 'Ben-Hur', 'Atlantis: The Lost Empire', 'Alvin and the Chipmunks: The Road Chip', 'Valkyrie', "You Don't Mess with the Zohan", 'Pixels', 'A.I. Artificial Intelligence', 'The Haunted Mansion', 'Contact', 'Hollow Man', 'The Interpreter', 'Percy Jackson: Sea of Monsters', 'Lara Croft Tomb Raider: The Cradle of Life', 'Now You See Me 2', 'The Saint', 'Spy Game', 'Mission to Mars', 'Rio', 'Bicentennial Man', 'Volcano', "The Devil's Own", 'K-19: The Widowmaker', 'Conan the Barbarian', 'Cinderella Man', 'The Nutcracker: The Untold Story', 'Seabiscuit', 'Twister', 'Cast Away', 'Happy Feet', 'The Bourne Supremacy', 'Air Force One', "Ocean's Eleven", 'The Three Musketeers', 'Hotel Transylvania', 'Enchanted', 'Safe House', '102 Dalmatians', 'Tower Heist', 'The Holiday', 'Enemy of the State', "It's Complicated", "Ocean's Thirteen", 'Open Season', 'Divergent', 'Enemy at the Gates', 'The Rundown', 'Last Action Hero', 'Memoirs of a Geisha', 'The Fast and the Furious: Tokyo Drift', 'Arthur Christmas', 'Meet Joe Black', 'Collateral Damage', 'All That Jazz', 'Mirror Mirror', 'Scott Pilgrim vs. the World', 'The Core', 'Nutty Professor II: The Klumps', 'Scooby-Doo', 'Dredd', 'Click', 'Creepshow', 'Cats & Dogs 2 : The Revenge of Kitty Galore', 'Jumper', 'Hellboy II: The Golden Army', 'Zodiac', 'The 6th Day', 'Bruce Almighty', 'The Expendables', 'Mission: Impossible', 'The Hunger Games', 'The Hangover Part II', 'Batman Returns', 'Over the Hedge', 'Lilo & Stitch', "Charlotte's Web", 'Deep Impact', 'RED 2', 'The Longest Yard', 'Alvin and the Chipmunks: Chipwrecked', 'Grown Ups 2', 'Get Smart', "Something's Gotta Give", 'Shutter Island', 'Four Christmases', 'Robots', 'Face/Off', 'Bedtime Stories', 'Road to Perdition', 'Just Go with It', 'Con Air', 'Eagle Eye', 'Cold Mountain', 'The Book of Eli', 'Flubber', 'The Haunting', 'Space Jam', 'The Pink Panther', 'The Day the Earth Stood Still', 'Conspiracy Theory', 'Fury', 'Six Days Seven Nights', 'Yogi Bear', 'Spirit: Stallion of the Cimarron', 'Zookeeper', 'Lost in Space', 'The Manchurian Candidate', 'Hotel Transylvania 2', 'Fantasia 2000', 'The Time Machine', 'Mighty Joe Young', 'Swordfish', 'The Legend of Zorro', 'What Dreams May Come', 'Little Nicky', 'The Brothers Grimm', 'Mars Attacks!', 'The Edge', 'Surrogates', 'Thirteen Days', 'Daylight', 'Walking With Dinosaurs', 'Battlefield Earth', 'Looney Tunes: Back in Action', 'Nine', 'Timeline', 'The Postman', 'Babe: Pig in the City', 'The Last Witch Hunter', 'Red Planet', 'Arthur et les Minimoys', 'Oceans', 'A Sound of Thunder', 'Pompeii', 'Don Gato: El inicio de la pandilla', 'A Beautiful Mind', 'The Lion King', 'Journey 2: The Mysterious Island', 'Cloudy with a Chance of Meatballs 2', 'Red Dragon', 'Hidalgo', 'Jack and Jill', '2 Fast 2 Furious', 'The Little Prince', 'The Invasion', 'The Adventures of Rocky & Bullwinkle', 'The Secret Life of Pets', 'The League of Extraordinary Gentlemen', 'Despicable Me 2', 'Independence Day', 'The Lost World: Jurassic Park', 'Madagascar', 'Children of Men', 'X-Men', 'Wanted', 'The Rock', 'Ice Age: The Meltdown', '50 First Dates', 'Hairspray', 'Exorcist: The Beginning', 'Inspector Gadget', 'Now You See Me', 'Grown Ups', 'The Terminal', 'Hotel for Dogs', 'Vertical Limit', "Charlie Wilson's War", 'Shark Tale', 'Dreamgirls', 'Be Cool', 'Munich', 'Tears of the Sun', 'Killers', 'The Man from U.N.C.L.E.', 'Spanglish', 'Monster House', 'Bandits', 'First Knight', 'Anna and the King', 'Immortals', 'Hostage', 'Titan A.E.', 'Hollywood Homicide', 'Soldier', 'Carriers', 'Monkeybone', 'Flight of the Phoenix', 'Unbreakable', 'Minions', 'Sucker Punch', 'Snake Eyes', 'Sphere', 'The Angry Birds Movie', "Fool's Gold", 'Funny People', 'The Kingdom', 'Talladega Nights: The Ballad of Ricky Bobby', 'Dr. Dolittle 2', 'Braveheart', 'Jarhead', 'The Simpsons Movie', 'The Majestic', 'Driven', 'Deux frères', 'The Village', 'Doctor Dolittle', 'Signs', 'Shrek 2', 'Cars', 'Runaway Bride', 'xXx', 'The SpongeBob Movie: Sponge Out of Water', 'Ransom', 'Inglourious Basterds', 'Hook', 'Die Hard 2', 'S.W.A.T.', 'Vanilla Sky', 'Lady in the Water', 'AVP: Alien vs. Predator', 'Alvin and the Chipmunks: The Squeakquel', 'We Were Soldiers', 'Olympus Has Fallen', 'Star Trek: Insurrection', 'Battle: Los Angeles', 'Big Fish', 'Wolf', 'War Horse', 'The Monuments Men', 'The Abyss', 'Wall Street: Money Never Sleeps', 'Dracula Untold', 'The Siege', 'Stardust', 'Seven Years in Tibet', 'The Dilemma', 'Bad Company', 'Doom', 'I Spy', 'Underworld: Awakening', 'Rock of Ages', "Hart's War", 'Killer Elite', 'Rollerball', 'Ballistic: Ecks vs. Sever', 'Hard Rain', 'Osmosis Jones', "Legends of Oz: Dorothy's Return", 'Blackhat', 'Sky Captain and the World of Tomorrow', 'Basic Instinct 2', 'Escape Plan', 'The Legend of Hercules', 'The Sum of All Fears', 'The Twilight Saga: Eclipse', 'The Score', 'Despicable Me', 'Money Train', 'Ted 2', 'Agora', 'Mystery Men', 'Hall Pass', 'The Insider', 'The Finest Hours', 'Body of Lies', 'Dinner for Schmucks', 'Abraham Lincoln: Vampire Hunter', 'Entrapment', 'The X Files', 'The Last Legion', 'Saving Private Ryan', 'Need for Speed', 'What Women Want', 'Ice Age', 'Dreamcatcher', 'Lincoln', 'The Matrix', 'Apollo 13', 'The Santa Clause 2', "You've Got Mail", 'Step Brothers', 'The Mask of Zorro', 'Due Date', 'Unbroken', 'Space Cowboys', 'Cliffhanger', 'Broken Arrow', 'The Kid', 'World Trade Center', 'Mona Lisa Smile', 'The Dictator', 'Eyes Wide Shut', 'Annie', 'Focus', 'This Means War', 'Blade: Trinity', 'Red Dawn', 'Primary Colors', 'Resident Evil: Retribution', 'Death Race', 'The Long Kiss Goodnight', 'Proof of Life', 'Zathura: A Space Adventure', 'Fight Club', 'We Are Marshall', 'Hudson Hawk', 'Lucky Numbers', 'I, Frankenstein', 'Oliver Twist', 'Elektra', 'Sin City: A Dame to Kill For', 'Random Hearts', 'Everest', 'Perfume: The Story of a Murderer', 'Austin Powers in Goldmember', 'Astro Boy', 'Jurassic Park', 'Wyatt Earp', 'Clear and Present Danger', 'Little Man', 'U-571', 'The American President', 'The Love Guru', '3000 Miles to Graceland', 'The Hateful Eight', 'Blades of Glory', 'Hop', 'Meet the Fockers', 'Marley & Me', 'The Green Mile', 'Wild Hogs', 'Chicken Little', 'Gone Girl', 'The Bourne Identity', 'GoldenEye', "The General's Daughter", 'The Truman Show', 'The Prince of Egypt', 'Daddy Day Care', '2 Guns', 'Cats & Dogs', 'The Italian Job', 'Two Weeks Notice', 'Antz', 'Couples Retreat', 'Days of Thunder', 'Cheaper by the Dozen 2', 'Maze Runner: The Scorch Trials', 'Eat Pray Love', 'The Family Man', 'RED', 'Any Given Sunday', 'The Horse Whisperer', 'Collateral', 'The Scorpion King', 'Ladder 49', 'Jack Reacher', 'Deep Blue Sea', "Michael Jackson's This Is It", 'Contagion', 'Kangaroo Jack', 'Coraline', 'The Happening', 'Man on Fire', 'The Shaggy Dog', 'Starsky & Hutch', 'Jingle All the Way', 'Hellboy', 'A Civil Action', 'ParaNorman', 'The Jackal', 'Paycheck', 'Up Close & Personal', 'The Tale of Despereaux', 'The Tuxedo', 'Under Siege 2: Dark Territory', 'Jack Ryan: Shadow Recruit', 'Joy', 'London Has Fallen', 'Alien: Resurrection', 'Shooter', 'The Boxtrolls', 'Practical Magic', 'The Lego Movie', 'Miss Congeniality 2: Armed and Fabulous', 'Reign of Fire', 'Gangster Squad', 'Year One', 'Invictus', 'State of Play', 'Duplicity', 'My Favorite Martian', 'The Sentinel', 'Planet 51', 'Star Trek: Nemesis', 'Intolerable Cruelty', 'Trouble with the Curve', 'Edge of Darkness', 'The Relic', 'Analyze That', 'Righteous Kill', 'Mercury Rising', 'The Soloist', 'The Legend of Bagger Vance', 'Almost Famous', 'Garfield: A Tail of Two Kitties', 'xXx: State of the Union', 'Priest', 'Sinbad: Legend of the Seven Seas', 'Event Horizon', 'Dragonfly', 'The Black Dahlia', 'Flyboys', 'The Last Castle', 'Supernova', "Winter's Tale", 'The Mortal Instruments: City of Bones', 'Meet Dave', 'Dark Water', 'Edtv', 'Inkheart', 'The Spirit', 'Mortdecai', 'In the Name of the King: A Dungeon Siege Tale', 'Beyond Borders', 'The Great Raid', 'Deadpool', 'Holy Man', 'American Sniper', 'Goosebumps', 'Just Like Heaven', 'The Flintstones in Viva Rock Vegas', 'Rambo III', 'Leatherheads', 'The Ridiculous 6', 'Did You Hear About the Morgans?', 'The Internship', 'Resident Evil: Afterlife', 'Red Tails', "The Devil's Advocate", "That's My Boy", 'DragonHeart', 'After the Sunset', 'Ghost Rider: Spirit of Vengeance', "Captain Corelli's Mandolin", 'The Pacifier', 'Walking Tall', 'Forrest Gump', 'Alvin and the Chipmunks', 'Meet the Parents', 'Pocahontas', 'Superman', 'The Nutty Professor', 'Hitch', 'George of the Jungle', 'American Wedding', 'Captain Phillips', 'Date Night', 'Casper', 'The Equalizer', 'Maid in Manhattan', 'Crimson Tide', 'The Pursuit of Happyness', 'Flightplan', 'Disclosure', 'City of Angels', 'Kill Bill: Vol. 1', 'Bowfinger', 'Kill Bill: Vol. 2', 'Tango & Cash', 'Death Becomes Her', 'Shanghai Noon', 'Executive Decision', "Mr. Popper's Penguins", 'The Forbidden Kingdom', 'Free Birds', 'Alien³', 'Evita', 'Ronin', 'The Ghost and the Darkness', 'Paddington', 'The Watch', 'The Hunted', 'Instinct', 'Stuck on You', 'Semi-Pro', 'The Pirates! In an Adventure with Scientists!', 'Changeling', 'Chain Reaction', 'The Fan', 'The Phantom of the Opera', 'Elizabeth: The Golden Age', 'Gods and Generals', 'Turbulence', 'Imagine That', 'Muppets Most Wanted', 'Thunderbirds', 'Burlesque', 'Un long dimanche de fiançailles', 'Lolita', 'D-Tox', 'Blade II', 'Seven Pounds', 'Bullet to the Head', 'The Godfather: Part III', 'Elizabethtown', 'You, Me and Dupree', 'Superman II', 'Gigli', "All the King's Men", 'Shaft', 'Anastasia', 'Moulin Rouge!', 'Domestic Disturbance', 'Black Mass', 'Flags of Our Fathers', 'Law Abiding Citizen', 'Grindhouse', 'Beloved', 'Lucky You', 'Catch Me If You Can', 'Zero Dark Thirty', 'The Break-Up', 'Mamma Mia!', "Valentine's Day", 'The Dukes of Hazzard', 'The Thin Red Line', 'The Change-Up', 'Man on the Moon', 'Casino', 'From Paris with Love', 'Bulletproof Monk', 'Me, Myself & Irene', 'Barnyard', 'Deck the Halls', 'The Twilight Saga: New Moon', 'Shrek', 'The Adjustment Bureau', 'Robin Hood: Prince of Thieves', 'Jerry Maguire', 'Ted', 'As Good as It Gets', 'Patch Adams', 'Anchorman 2: The Legend Continues', 'Mr. Deeds', 'Super 8', 'Erin Brockovich', 'How to Lose a Guy in 10 Days', '22 Jump Street', 'Interview with the Vampire', 'Yes Man', 'Central Intelligence', 'Stepmom', "Daddy's Home", 'Into the Woods', 'Inside Man', 'Payback', 'Congo', 'We Bought a Zoo', 'Knowing', 'Failure to Launch', 'The Ring Two', 'Crazy, Stupid, Love.', 'Garfield', 'Christmas with the Kranks', 'Moneyball', 'Outbreak', 'Non-Stop', 'Race to Witch Mountain', 'V for Vendetta', 'Shanghai Knights', 'Curious George', 'Herbie Fully Loaded', "Don't Say a Word", 'Hansel & Gretel: Witch Hunters', 'Unfaithful', 'I Am Number Four', 'Syriana', '13 Hours: The Secret Soldiers of Benghazi', 'The Book of Life', 'Firewall', 'Absolute Power', 'G.I. Jane', 'The Game', 'Silent Hill', 'The Replacements', 'American Reunion', 'The Negotiator', 'Into the Storm', 'Beverly Hills Cop III', 'Gremlins 2: The New Batch', 'The Judge', 'The Peacemaker', 'Resident Evil: Apocalypse', 'Bridget Jones: The Edge of Reason', 'Out of Time', 'On Deadly Ground', 'The Adventures of Sharkboy and Lavagirl', 'The Beach', 'Raising Helen', 'Ninja Assassin', 'For Love of the Game', 'Striptease', 'Marmaduke', 'Hereafter', 'Murder by Numbers', 'Assassins', 'Hannibal Rising', 'The Story of Us', 'The Host', 'Basic', 'Blood Work', 'The International', 'Escape from L.A.', 'The Iron Giant', 'The Life Aquatic with Steve Zissou', 'Free State of Jones', 'The Life of David Gale', 'Man of the House', 'Run All Night', 'Eastern Promises', 'Into the Blue', 'Joan of Arc', 'Your Highness', 'Dream House', 'Mad City', "Baby's Day Out", 'The Scarlet Letter', 'Fair Game', 'Domino', 'Jade', 'Gamer', 'Beautiful Creatures', 'Death to Smoochy', 'Zoolander 2', 'The Big Bounce', 'What Planet Are You From?', 'Drive Angry', 'Street Fighter: The Legend of Chun-Li', 'The One', 'The Adventures of Ford Fairlane', 'The Boat That Rocked', 'Traffic', 'Indiana Jones and the Last Crusade', 'Anna Karenina', 'Chappie', 'The Bone Collector', 'Panic Room', 'Th

In [12]:
# getting the movie name from the user
movie_name = input("Enter your favourite movie name : ")

Enter your favourite movie name : avtar

In [13]:
# finding the close match for the movie name given by the user

import difflib
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['Avatar', 'Salvador', 'Water']

In [14]:
close_match = find_close_match[0]
print(close_match)

Avatar

In [20]:
# finding the index of the movie with title

index_of_the_movie = df[df.title == close_match]['index'].values[0]
print(index_of_the_movie)

0

In [16]:
# getting a list of similar movies

similarity_score = list(enumerate(similarity[index_of_the_movie]))
similarity_score

[(0, 1.0),
 (1, 0.7461881038084348),
 (2, 0.4300932725421497),
 (3, 0.18279968246381667),
 (4, 0.8618583280376579),
 (5, 0.7461881038084348),
 (6, 0.0),
 (7, 0.8618583280376579),
 (8, 0.5290709893371626),
 (9, 0.7461881038084348),
 (10, 1.0),
 (11, 0.3857676063897863),
 (12, 0.7461881038084348),
 (13, 0.32377190156512214),
 (14, 1.0),
 (15, 0.5290709893371626),
 (16, 0.8618583280376579),
 (17, 0.7461881038084348),
 (18, 0.7042907626913639),
 (19, 0.7461881038084348),
 (20, 0.7461881038084348),
 (21, 0.5473540571450023),
 (22, 0.6540411126738399),
 (23, 0.6540411126738399),
 (24, 0.49574097409800466),
 (25, 0.0),
 (26, 0.8618583280376579),
 (27, 0.8006490857791303),
 (28, 0.8006490857791303),
 (29, 0.46366321153025025),
 (30, 0.7461881038084348),
 (31, 0.8618583280376579),
 (32, 0.5290709893371626),
 (33, 0.8006490857791303),
 (34, 0.0),
 (35, 0.8618583280376579),
 (36, 0.8618583280376579),
 (37, 0.5290709893371626),
 (38, 0.7461881038084348),
 (39, 0.8618583280376579),
 (40, 0.18632670348671124),
 (41, 0.8006490857791303),
 (42, 0.0),
 (43, 0.6888119047171325),
 (44, 0.3592031586687302),
 (45, 0.5778561548342801),
 (46, 1.0),
 (47, 0.8618583280376579),
 (48, 0.49363263928743273),
 (49, 0.0),
 (50, 0.6599030515783392),
 (51, 0.8618583280376579),
 (52, 0.8618583280376579),
 (53, 0.5473540571450023),
 (54, 0.1969429882013062),
 (55, 0.3046587006284951),
 (56, 0.8618583280376579),
 (57, 0.0),
 (58, 0.17884427348406015),
 (59, 0.0),
 (60, 1.0),
 (61, 0.5473540571450023),
 (62, 0.5290709893371626),
 (63, 0.6657351678669022),
 (64, 0.18279968246381667),
 (65, 0.18632670348671124),
 (66, 0.5618642206743563),
 (67, 0.8618583280376579),
 (68, 0.2509049204472478),
 (69, 0.6306349482370464),
 (70, 0.7461881038084348),
 (71, 0.9183847760049734),
 (72, 0.34035269025037707),
 (73, 0.7564590028100435),
 (74, 0.5473540571450023),
 (75, 0.8006490857791303),
 (76, 0.0),
 (77, 0.5043585118731458),
 (78, 0.8618583280376579),
 (79, 0.6089898708504605),
 (80, 0.5749424766328737),
 (81, 0.6582247264216019),
 (82, 0.7838834127633749),
 (83, 0.7057519726317154),
 (84, 0.8618583280376579),
 (85, 0.40875206958004623),
 (86, 0.5786703757351834),
 (87, 0.3046587006284951),
 (88, 0.18632670348671124),
 (89, 0.4262158368635772),
 (90, 0.8618583280376579),
 (91, 0.4262158368635772),
 (92, 0.6888119047171325),
 (93, 0.8618583280376579),
 (94, 0.7446352589859611),
 (95, 0.6938747226326046),
 (96, 0.7461881038084348),
 (97, 0.1961775368980903),
 (98, 0.27399746282678855),
 (99, 0.8618583280376579),
 (100, 0.8618583280376579),
 (101, 0.6606378964917216),
 (102, 0.4310216637198509),
 (103, 0.5071491125814311),
 (104, 0.40875206958004623),
 (105, 0.7461881038084348),
 (106, 0.8006490857791303),
 (107, 0.5290709893371626),
 (108, 0.0),
 (109, 0.8618583280376579),
 (110, 0.27271585677019455),
 (111, 0.44144622332069006),
 (112, 0.5290709893371626),
 (113, 0.6214717464130821),
 (114, 0.5778561548342801),
 (115, 0.4967245172277753),
 (116, 0.26747500223167026),
 (117, 0.20922886463583648),
 (118, 0.0),
 (119, 0.5967224634900683),
 (120, 0.8006490857791303),
 (121, 0.8006490857791303),
 (122, 0.1969429882013062),
 (123, 0.8006490857791303),
 (124, 0.7461881038084348),
 (125, 0.8006490857791303),
 (126, 0.0),
 (127, 0.7461881038084348),
 (128, 0.18632670348671124),
 (129, 0.5967224634900683),
 (130, 0.4130006715194316),
 (131, 0.4378154525050026),
 (132, 0.46366321153025025),
 (133, 0.0),
 (134, 0.18632670348671124),
 (135, 0.0),
 (136, 0.629340588081369),
 (137, 0.46366321153025025),
 (138, 0.23078344851126767),
 (139, 0.1969429882013062),
 (140, 0.18632670348671124),
 (141, 0.5290709893371626),
 (142, 0.1969429882013062),
 (143, 0.20625279150609527),
 (144, 0.0),
 (145, 0.46366321153025025),
 (146, 0.5609056539584171),
 (147, 0.8006490857791303),
 (148, 0.8149792404225792),
 (149, 0.37069778395286934),
 (150, 0.3046587006284951),
 (151, 0.46366321153025025),
 (152, 0.2811753423043841),
 (153, 0.0),
 (154, 0.12674827439488617),
 (155, 0.49574097409800466),
 (156, 0.8618583280376579),
 (157, 0.6214717464130821),
 (158, 0.5572724880470459),
 (159, 0.5071491125814311),
 (160, 0.3592031586687302),
 (161, 0.6179479437974634),
 (162, 0.3603957434033572),
 (163, 0.7164858259730101),
 (164, 0.8006490857791303),
 (165, 0.3486469532702716),
 (166, 0.8595226897763959),
 (167, 0.8618583280376579),
 (168, 0.46366321153025025),
 (169, 0.4130006715194316),
 (170, 0.5311851888529373),
 (171, 0.0),
 (172, 0.8618583280376579),
 (173, 0.5290709893371626),
 (174, 0.17873104084489286),
 (175, 0.0),
 (176, 0.14443332183164997),
 (177, 0.18632670348671124),
 (178, 0.1668722866230701),
 (179, 0.18632670348671124),
 (180, 0.8618583280376579),
 (181, 0.8618583280376579),
 (182, 0.5988650061034313),
 (183, 0.7175379075672442),
 (184, 0.3603957434033572),
 (185, 0.5223288610385075),
 (186, 0.1768622952361049),
 (187, 0.35096258618799064),
 (188, 0.18958834288140355),
 (189, 0.5290709893371626),
 (190, 0.0),
 (191, 0.8618583280376579),
 (192, 0.0),
 (193, 0.4967245172277753),
 (194, 0.5139447125043662),
 (195, 0.5290709893371626),
 (196, 0.4754944137609941),
 (197, 0.7461881038084348),
 (198, 0.7175379075672442),
 (199, 0.0),
 (200, 0.18632670348671124),
 (201, 0.8006490857791303),
 (202, 0.1961775368980903),
 (203, 0.341309398785432),
 (204, 0.7461881038084348),
 (205, 0.8618583280376579),
 (206, 0.7461881038084348),
 (207, 0.25964691135721524),
 (208, 0.5107371933333631),
 (209, 0.34035269025037707),
 (210, 0.8006490857791303),
 (211, 0.46366321153025025),
 (212, 0.0),
 (213, 0.6778562796071878),
 (214, 0.49574097409800466),
 (215, 0.4523581098446353),
 (216, 0.25964691135721524),
 (217, 0.4812780025008105),
 (218, 0.6473151764032059),
 (219, 0.18632670348671124),
 (220, 0.6582247264216019),
 (221, 0.7564590028100435),
 (222, 0.7564590028100435),
 (223, 0.6405013277794869),
 (224, 0.0),
 (225, 0.277020197507906),
 (226, 0.7325866237304618),
 (227, 0.8618583280376579),
 (228, 0.8618583280376579),
 (229, 0.0),
 (230, 1.0),
 (231, 0.8618583280376579),
 (232, 0.40875206958004623),
 (233, 0.12674827439488617),
 (234, 0.49574097409800466),
 (235, 0.9587449509121917),
 (236, 0.559829888719476),
 (237, 0.46366321153025025),
 (238, 0.6934494950898689),
 (239, 0.8618583280376579),
 (240, 0.5967224634900683),
 (241, 0.23078344851126767),
 (242, 0.46366321153025025),
 (243, 0.12674827439488617),
 (244, 0.0),
 (245, 0.2038858888070071),
 (246, 0.7175379075672442),
 (247, 0.0),
 (248, 0.0),
 (249, 0.20335644641109127),
 (250, 0.16989833167333654),
 (251, 0.40875206958004623),
 (252, 0.0),
 (253, 0.7834365758695939),
 (254, 0.7164858259730101),
 (255, 0.26747500223167026),
 (256, 0.46366321153025025),
 (257, 0.8618583280376579),
 (258, 0.25964691135721524),
 (259, 0.7461881038084348),
 (260, 0.4812780025008105),
 (261, 0.0),
 (262, 0.34035269025037707),
 (263, 0.7564590028100435),
 (264, 0.27271585677019455),
 (265, 0.26747500223167026),
 (266, 0.0),
 (267, 0.7446352589859611),
 (268, 0.8006490857791303),
 (269, 0.0),
 (270, 0.1961775368980903),
 (271, 0.49574097409800466),
 (272, 0.5793947164915025),
 (273, 0.5290709893371626),
 (274, 0.46366321153025025),
 (275, 0.8006490857791303),
 (276, 0.6888119047171325),
 (277, 0.0),
 (278, 0.0),
 (279, 0.25964691135721524),
 (280, 0.0),
 (281, 0.0),
 (282, 0.20335644641109127),
 (283, 0.1668722866230701),
 (284, 0.0),
 (285, 0.0),
 (286, 0.40875206958004623),
 (287, 0.46366321153025025),
 (288, 0.3573752372621125),
 (289, 0.629340588081369),
 (290, 0.37002391333728296),
 (291, 0.4262158368635772),
 (292, 0.20348415400066142),
 (293, 0.40794697547308667),
 (294, 0.23078344851126767),
 (295, 0.0),
 (296, 0.5107371933333631),
 (297, 0.8006490857791303),
 (298, 0.6213190840290798),
 (299, 0.4262158368635772),
 (300, 0.2300164471484523),
 (301, 0.5473540571450023),
 (302, 0.7231770119130426),
 (303, 0.7327175432616259),
 (304, 0.46366321153025025),
 (305, 0.1961775368980903),
 (306, 0.4967245172277753),
 (307, 0.3199081828101542),
 (308, 0.7042907626913639),
 (309, 0.310523761455068),
 (310, 0.0),
 (311, 0.0),
 (312, 0.7461881038084348),
 (313, 0.0),
 (314, 0.0),
 (315, 0.7042907626913639),
 (316, 0.1309632931818997),
 (317, 0.0),
 (318, 0.9457920678395555),
 (319, 0.0),
 (320, 0.18632670348671124),
 (321, 0.18632670348671124),
 (322, 0.30655834757320105),
 (323, 0.45267175896539386),
 (324, 0.0),
 (325, 0.7461881038084348),
 (326, 0.7461881038084348),
 (327, 0.6540411126738399),
 (328, 0.6778562796071878),
 (329, 0.4640869100697549),
 (330, 0.8006490857791303),
 (331, 0.6582247264216019),
 (332, 0.5290709893371626),
 (333, 0.25964691135721524),
 (334, 0.0),
 (335, 0.31952856830544074),
 (336, 0.5473540571450023),
 (337, 0.5290709893371626),
 (338, 0.8149792404225792),
 (339, 0.0),
 (340, 0.25964691135721524),
 (341, 0.17884427348406015),
 (342, 0.0),
 (343, 0.0),
 (344, 0.18632670348671124),
 (345, 0.5610544571110924),
 (346, 0.3603957434033572),
 (347, 0.0),
 (348, 0.1969429882013062),
 (349, 0.277020197507906),
 (350, 0.0),
 (351, 0.25964691135721524),
 (352, 0.341309398785432),
 (353, 0.0),
 (354, 0.5618642206743563),
 (355, 0.18632670348671124),
 (356, 0.0),
 (357, 0.277020197507906),
 (358, 0.7042907626913639),
 (359, 0.7446352589859611),
 (360, 0.2605763505450543),
 (361, 0.49735012231765807),
 (362, 0.6888119047171325),
 (363, 0.0),
 (364, 0.5290709893371626),
 (365, 0.6778562796071878),
 (366, 0.32336042131974874),
 (367, 0.736985505569561),
 (368, 0.1961775368980903),
 (369, 0.6657351678669022),
 (370, 0.18632670348671124),
 (371, 0.6081469493683327),
 (372, 0.6582247264216019),
 (373, 0.0),
 (374, 0.0),
 (375, 0.7461881038084348),
 (376, 0.0),
 (377, 0.49363263928743273),
 (378, 0.0),
 (379, 0.49574097409800466),
 (380, 0.35096258618799064),
 (381, 0.0),
 (382, 0.23078344851126767),
 (383, 0.25964691135721524),
 (384, 0.0),
 (385, 0.46366321153025025),
 (386, 0.26747500223167026),
 (387, 0.3018188143593182),
 (388, 0.25964691135721524),
 (389, 0.0),
 (390, 0.277020197507906),
 (391, 0.0),
 (392, 0.23078344851126767),
 (393, 0.0),
 (394, 0.0),
 (395, 0.1969429882013062),
 (396, 0.8618583280376579),
 (397, 0.0),
 (398, 0.4214140943573673),
 (399, 0.5967224634900683),
 (400, 0.0),
 (401, 0.18279968246381667),
 (402, 0.0),
 (403, 0.3298228955170305),
 (404, 0.23078344851126767),
 (405, 0.0),
 (406, 0.8604888805194488),
 (407, 0.4812780025008105),
 (408, 0.8006490857791303),
 (409, 0.7210920970600688),
 (410, 0.23131212601222623),
 (411, 0.7564590028100435),
 (412, 0.3419109745670683),
 (413, 0.3406822016004416),
 (414, 0.0),
 (415, 0.9332593909532371),
 (416, 0.9332593909532371),
 (417, 0.0),
 (418, 0.6657351678669022),
 (419, 0.4378154525050026),
 (420, 0.46366321153025025),
 (421, 0.46366321153025025),
 (422, 0.9332593909532371),
 (423, 0.0),
 (424, 0.6214717464130821),
 (425, 0.0),
 (426, 0.0),
 (427, 0.34035269025037707),
 (428, 0.21816246846835463),
 (429, 0.17884427348406015),
 (430, 0.0),
 (431, 0.22407432357719625),
 (432, 0.0),
 (433, 0.22297322645632195),
 (434, 0.0),
 (435, 0.0),
 (436, 0.0),
 (437, 0.4205467096540001),
 (438, 0.6114677353971785),
 (439, 0.3018188143593182),
 (440, 0.0),
 (441, 0.0),
 (442, 0.1961775368980903),
 (443, 0.1768622952361049),
 (444, 0.0),
 (445, 0.6888119047171325),
 (446, 0.509373087283145),
 (447, 0.27336387063487594),
 (448, 0.2584595421565809),
 (449, 0.1349753484492457),
 (450, 0.559829888719476),
 (451, 0.1668722866230701),
 (452, 0.16098529849318138),
 (453, 0.4067081041467556),
 (454, 0.18632670348671124),
 (455, 0.14443332183164997),
 (456, 0.0),
 (457, 0.6697911949672056),
 (458, 0.0),
 (459, 0.0),
 (460, 0.0),
 (461, 0.8618583280376579),
 (462, 0.629340588081369),
 (463, 0.1961775368980903),
 (464, 0.5473540571450023),
 (465, 0.37202881213573435),
 (466, 0.36364926910398926),
 (467, 0.6375900715887174),
 (468, 0.7888569397599432),
 (469, 0.49574097409800466),
 (470, 0.6888119047171325),
 (471, 0.0),
 (472, 0.46366321153025025),
 (473, 0.1969429882013062),
 (474, 0.5666072506901773),
 (475, 0.0),
 (476, 0.0),
 (477, 0.8618583280376579),
 (478, 0.35096258618799064),
 (479, 0.4761044661011189),
 (480, 0.7461881038084348),
 (481, 0.6888119047171325),
 (482, 0.4262158368635772),
 (483, 0.0),
 (484, 0.8006490857791303),
 (485, 0.31333019739790186),
 (486, 0.0),
 (487, 0.0),
 (488, 0.0),
 (489, 0.8618583280376579),
 (490, 0.0),
 (491, 0.0),
 (492, 0.20001885701778296),
 (493, 0.0),
 (494, 0.1961775368980903),
 (495, 0.48393402267419394),
 (496, 0.5916650212462033),
 (497, 0.3046587006284951),
 (498, 0.0),
 (499, 0.8521692456510377),
 (500, 0.0),
 (501, 0.8618583280376579),
 (502, 0.8618583280376579),
 (503, 0.0),
 (504, 0.6582247264216019),
 (505, 0.8618583280376579),
 (506, 0.1961775368980903),
 (507, 0.46366321153025025),
 (508, 0.18632670348671124),
 (509, 0.0),
 (510, 0.0),
 (511, 0.0),
 (512, 0.3825107944144963),
 (513, 0.0),
 (514, 0.0),
 (515, 0.0),
 (516, 0.0),
 (517, 0.46366321153025025),
 (518, 0.0),
 (519, 0.14457539745398573),
 (520, 0.0),
 (521, 0.0),
 (522, 0.15350808955293332),
 (523, 0.16098529849318138),
 (524, 0.1843279121705368),
 (525, 0.4812780025008105),
 (526, 0.0),
 (527, 0.26747500223167026),
 (528, 0.17277473174264643),
 (529, 0.4153241917525058),
 (530, 0.0),
 (531, 0.5745682233480152),
 (532, 0.0),
 (533, 0.6459531244916336),
 (534, 0.4214140943573673),
 (535, 0.5666072506901773),
 (536, 0.5778561548342801),
 (537, 0.5572724880470459),
 (538, 0.4310216637198509),
 (539, 0.559829888719476),
 (540, 0.18632670348671124),
 (541, 0.543959308630883),
 (542, 0.0),
 (543, 0.6657351678669022),
 (544, 0.0),
 (545, 0.2652204826488394),
 (546, 0.0),
 (547, 0.23078344851126767),
 (548, 0.0),
 (549, 0.3018188143593182),
 (550, 0.12674827439488617),
 (551, 0.0),
 (552, 0.0),
 (553, 0.0),
 (554, 0.3592031586687302),
 (555, 0.2509049204472478),
 (556, 0.0),
 (557, 0.34035269025037707),
 (558, 0.4640869100697549),
 (559, 0.40875206958004623),
 (560, 0.18632670348671124),
 (561, 0.0),
 (562, 0.46366321153025025),
 (563, 0.18632670348671124),
 (564, 0.25964691135721524),
 (565, 0.14797588406081155),
 (566, 0.4967245172277753),
 (567, 0.25964691135721524),
 (568, 0.1961775368980903),
 (569, 0.42903205160337515),
 (570, 0.3018534120552869),
 (571, 0.8618583280376579),
 (572, 0.22407432357719625),
 (573, 0.1309632931818997),
 (574, 0.25964691135721524),
 (575, 0.8006490857791303),
 (576, 0.7564590028100435),
 (577, 0.6089898708504605),
 (578, 0.5071491125814311),
 (579, 0.0),
 (580, 0.12674827439488617),
 (581, 0.8006490857791303),
 (582, 0.0),
 (583, 0.36423210994266214),
 (584, 0.18279968246381667),
 (585, 0.47563837363964906),
 (586, 0.2148795347384682),
 (587, 0.0),
 (588, 0.4214140943573673),
 (589, 0.413701787620786),
 (590, 0.4214140943573673),
 (591, 0.494078407577436),
 (592, 0.0),
 (593, 0.0),
 (594, 0.46366321153025025),
 (595, 0.6888119047171325),
 (596, 0.46366321153025025),
 (597, 0.0),
 (598, 0.3046587006284951),
 (599, 0.0),
 (600, 0.0),
 (601, 0.6938747226326046),
 (602, 0.0),
 (603, 0.25964691135721524),
 (604, 0.5473540571450023),
 (605, 0.23078344851126767),
 (606, 0.5311851888529373),
 (607, 0.1961775368980903),
 (608, 0.0),
 (609, 0.20335644641109127),
 (610, 0.0),
 (611, 0.2148795347384682),
 (612, 0.9587449509121917),
 (613, 0.0),
 (614, 0.0),
 (615, 0.15350808955293332),
 (616, 0.23078344851126767),
 (617, 0.0),
 (618, 0.494078407577436),
 (619, 0.0),
 (620, 0.48174414481429734),
 (621, 0.5555445628951303),
 (622, 0.0),
 (623, 0.18279968246381667),
 (624, 0.0),
 (625, 0.18632670348671124),
 (626, 0.4802707713051576),
 (627, 0.0),
 (628, 0.7564590028100435),
 (629, 0.0),
 (630, 0.34035269025037707),
 (631, 0.0),
 (632, 0.0),
 (633, 0.5473540571450023),
 (634, 0.0),
 (635, 0.0),
 (636, 0.46366321153025025),
 (637, 0.46366321153025025),
 (638, 0.4310216637198509),
 (639, 0.34035269025037707),
 (640, 0.0),
 (641, 0.0),
 (642, 0.0),
 (643, 0.0),
 (644, 0.0),
 (645, 0.0),
 (646, 0.21152937677701397),
 (647, 0.7129262072989797),
 (648, 0.25964691135721524),
 (649, 0.0),
 (650, 0.6409447980821701),
 (651, 0.6888119047171325),
 (652, 0.1522869338416573),
 (653, 0.37500314152734826),
 (654, 0.831603765690405),
 (655, 0.0),
 (656, 0.0),
 (657, 0.4812780025008105),
 (658, 0.3510676413747288),
 (659, 0.0),
 (660, 0.0),
 (661, 0.6214717464130821),
 (662, 0.0),
 (663, 0.0),
 (664, 0.35096258618799064),
 (665, 0.3606953958085056),
 (666, 0.5235031663394644),
 (667, 0.5331982948420113),
 (668, 0.7834365758695939),
 (669, 0.14885840740222356),
 (670, 0.23078344851126767),
 (671, 0.0),
 (672, 0.14797588406081155),
 (673, 0.0),
 (674, 0.0),
 (675, 0.3603957434033572),
 (676, 0.0),
 (677, 0.24272641255868702),
 (678, 0.0),
 (679, 0.0),
 (680, 0.0),
 (681, 0.3606953958085056),
 (682, 0.4812780025008105),
 (683, 0.0),
 (684, 0.0),
 (685, 0.1668722866230701),
 (686, 0.46366321153025025),
 (687, 0.0),
 (688, 0.0),
 (689, 0.1551522243579454),
 (690, 0.0),
 (691, 0.20335644641109127),
 (692, 0.0),
 (693, 0.2300164471484523),
 (694, 0.0),
 (695, 0.18632670348671124),
 (696, 0.0),
 (697, 0.4130006715194316),
 (698, 0.0),
 (699, 0.3592031586687302),
 (700, 0.0),
 (701, 0.3419109745670683),
 (702, 0.3603957434033572),
 (703, 0.0),
 (704, 0.0),
 (705, 0.0),
 (706, 0.7461881038084348),
 (707, 0.23078344851126767),
 (708, 0.0),
 (709, 0.6888119047171325),
 (710, 0.0),
 (711, 0.559829888719476),
 (712, 0.2559490098863143),
 (713, 0.0),
 (714, 0.5916650212462033),
 (715, 0.18279968246381667),
 (716, 0.0),
 (717, 0.0),
 (718, 0.0),
 (719, 0.9107307205340658),
 (720, 0.0),
 (721, 0.18632670348671124),
 (722, 0.3857676063897863),
 (723, 0.6938747226326046),
 (724, 0.0),
 (725, 0.1969429882013062),
 (726, 0.6487316254296273),
 (727, 0.25964691135721524),
 (728, 0.23078344851126767),
 (729, 0.0),
 (730, 0.1961775368980903),
 (731, 0.6409447980821701),
 (732, 0.1457690273306541),
 (733, 0.26747500223167026),
 (734, 0.40131549635776725),
 (735, 0.40875206958004623),
 (736, 0.277020197507906),
 (737, 0.7461881038084348),
 (738, 0.18279968246381667),
 (739, 0.33549544263692765),
 (740, 0.0),
 (741, 0.3592031586687302),
 (742, 0.0),
 (743, 0.48863306549339003),
 (744, 0.1961775368980903),
 (745, 0.5422452774499107),
 (746, 0.8006490857791303),
 (747, 0.0),
 (748, 0.0),
 (749, 0.0),
 (750, 0.0),
 (751, 0.0),
 (752, 0.18279968246381667),
 (753, 0.18279968246381667),
 (754, 0.0),
 (755, 0.45267175896539386),
 (756, 0.0),
 (757, 0.0),
 (758, 0.32764044375951185),
 (759, 0.7660914117281696),
 (760, 0.1969429882013062),
 (761, 0.45392280665289053),
 (762, 0.0),
 (763, 0.0),
 (764, 0.31333019739790186),
 (765, 0.23078344851126767),
 (766, 0.4999210550431027),
 (767, 0.2944030180847726),
 (768, 0.3337863614850976),
 (769, 0.6372632669284753),
 (770, 0.0),
 (771, 0.0),
 (772, 0.5290709893371626),
 (773, 0.5829104974557373),
 (774, 0.33549544263692765),
 (775, 0.7057519726317154),
 (776, 0.18621272107201883),
 (777, 0.1309632931818997),
 (778, 0.4812780025008105),
 (779, 0.0),
 (780, 0.16989833167333654),
 (781, 0.24534673698324536),
 (782, 0.36364926910398926),
 (783, 0.4640445644224179),
 (784, 0.3220858009076686),
 (785, 0.0),
 (786, 0.0),
 (787, 0.0),
 (788, 0.0),
 (789, 0.755115467733458),
 (790, 0.27271585677019455),
 (791, 0.0),
 (792, 0.0),
 (793, 0.5071491125814311),
 (794, 0.18856565345240736),
 (795, 0.543959308630883),
 (796, 0.0),
 (797, 0.16302039320133296),
 (798, 0.4310216637198509),
 (799, 0.0),
 (800, 0.22407432357719625),
 (801, 0.0),
 (802, 0.18885420842054768),
 (803, 1.0),
 (804, 0.7210920970600688),
 (805, 0.0),
 (806, 0.21328544044132863),
 (807, 0.0),
 (808, 0.23078344851126767),
 (809, 0.0),
 (810, 0.34035269025037707),
 (811, 0.1961775368980903),
 (812, 0.0),
 (813, 0.23078344851126767),
 (814, 0.0),
 (815, 0.0),
 (816, 0.0),
 (817, 0.37202881213573435),
 (818, 0.2300164471484523),
 (819, 0.0),
 (820, 0.1961775368980903),
 (821, 0.4812780025008105),
 (822, 0.4378154525050026),
 (823, 0.3083300841664923),
 (824, 0.4310216637198509),
 (825, 0.0),
 (826, 0.7461881038084348),
 (827, 0.0),
 (828, 0.6409447980821701),
 (829, 0.0),
 (830, 0.3857676063897863),
 (831, 0.4130006715194316),
 (832, 0.0),
 (833, 0.0),

In [17]:
len(similarity_score)

4693

In [18]:
# sorting the movies based on their similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
sorted_similar_movies

[(0, 1.0),
 (10, 1.0),
 (14, 1.0),
 (46, 1.0),
 (60, 1.0),
 (230, 1.0),
 (803, 1.0),
 (859, 1.0),
 (3420, 1.0),
 (235, 0.9587449509121917),
 (612, 0.9587449509121917),
 (1176, 0.9587449509121917),
 (1280, 0.9587449509121917),
 (1906, 0.9587449509121917),
 (318, 0.9457920678395555),
 (1215, 0.9457920678395555),
 (1371, 0.9457920678395555),
 (1629, 0.9457920678395555),
 (415, 0.9332593909532371),
 (416, 0.9332593909532371),
 (422, 0.9332593909532371),
 (71, 0.9183847760049734),
 (719, 0.9107307205340658),
 (1589, 0.9107307205340658),
 (1776, 0.9107307205340658),
 (2548, 0.9107307205340658),
 (1177, 0.9035643785487472),
 (2131, 0.9035643785487472),
 (1910, 0.8659926315532933),
 (4, 0.8618583280376579),
 (7, 0.8618583280376579),
 (16, 0.8618583280376579),
 (26, 0.8618583280376579),
 (31, 0.8618583280376579),
 (35, 0.8618583280376579),
 (36, 0.8618583280376579),
 (39, 0.8618583280376579),
 (47, 0.8618583280376579),
 (51, 0.8618583280376579),
 (52, 0.8618583280376579),
 (56, 0.8618583280376579),
 (67, 0.8618583280376579),
 (78, 0.8618583280376579),
 (84, 0.8618583280376579),
 (90, 0.8618583280376579),
 (93, 0.8618583280376579),
 (99, 0.8618583280376579),
 (100, 0.8618583280376579),
 (109, 0.8618583280376579),
 (156, 0.8618583280376579),
 (167, 0.8618583280376579),
 (172, 0.8618583280376579),
 (180, 0.8618583280376579),
 (181, 0.8618583280376579),
 (191, 0.8618583280376579),
 (205, 0.8618583280376579),
 (227, 0.8618583280376579),
 (228, 0.8618583280376579),
 (231, 0.8618583280376579),
 (239, 0.8618583280376579),
 (257, 0.8618583280376579),
 (396, 0.8618583280376579),
 (461, 0.8618583280376579),
 (477, 0.8618583280376579),
 (489, 0.8618583280376579),
 (501, 0.8618583280376579),
 (502, 0.8618583280376579),
 (505, 0.8618583280376579),
 (571, 0.8618583280376579),
 (1067, 0.8618583280376579),
 (1470, 0.8618583280376579),
 (1961, 0.8618583280376579),
 (2330, 0.8618583280376579),
 (2391, 0.8618583280376579),
 (2402, 0.8618583280376579),
 (2450, 0.8618583280376579),
 (2854, 0.8618583280376579),
 (2936, 0.8618583280376579),
 (3238, 0.8618583280376579),
 (3953, 0.8618583280376579),
 (4026, 0.8618583280376579),
 (406, 0.8604888805194488),
 (166, 0.8595226897763959),
 (3144, 0.8595226897763959),
 (499, 0.8521692456510377),
 (1097, 0.8521692456510377),
 (1324, 0.8521692456510377),
 (654, 0.831603765690405),
 (2908, 0.831603765690405),
 (148, 0.8149792404225792),
 (338, 0.8149792404225792),
 (27, 0.8006490857791303),
 (28, 0.8006490857791303),
 (33, 0.8006490857791303),
 (41, 0.8006490857791303),
 (75, 0.8006490857791303),
 (106, 0.8006490857791303),
 (120, 0.8006490857791303),
 (121, 0.8006490857791303),
 (123, 0.8006490857791303),
 (125, 0.8006490857791303),
 (147, 0.8006490857791303),
 (164, 0.8006490857791303),
 (201, 0.8006490857791303),
 (210, 0.8006490857791303),
 (268, 0.8006490857791303),
 (275, 0.8006490857791303),
 (297, 0.8006490857791303),
 (330, 0.8006490857791303),
 (408, 0.8006490857791303),
 (484, 0.8006490857791303),
 (575, 0.8006490857791303),
 (581, 0.8006490857791303),
 (746, 0.8006490857791303),
 (928, 0.8006490857791303),
 (965, 0.8006490857791303),
 (990, 0.8006490857791303),
 (1022, 0.8006490857791303),
 (1071, 0.8006490857791303),
 (1186, 0.8006490857791303),
 (1278, 0.8006490857791303),
 (1287, 0.8006490857791303),
 (1509, 0.8006490857791303),
 (1561, 0.8006490857791303),
 (1724, 0.8006490857791303),
 (2034, 0.8006490857791303),
 (2276, 0.8006490857791303),
 (2286, 0.8006490857791303),
 (2764, 0.8006490857791303),
 (3987, 0.8006490857791303),
 (4565, 0.8006490857791303),
 (4069, 0.8002470500517369),
 (4303, 0.8002470500517369),
 (1074, 0.8001576709112855),
 (2095, 0.8001576709112855),
 (2775, 0.8001576709112855),
 (920, 0.7902152563710952),
 (468, 0.7888569397599432),
 (1073, 0.7888569397599432),
 (1244, 0.7888569397599432),
 (1259, 0.7888569397599432),
 (1620, 0.7888569397599432),
 (3318, 0.7888569397599432),
 (3718, 0.7888569397599432),
 (2400, 0.784575258337251),
 (82, 0.7838834127633749),
 (3282, 0.7838834127633749),
 (253, 0.7834365758695939),
 (668, 0.7834365758695939),
 (1309, 0.7834365758695939),
 (1931, 0.7834365758695939),
 (3333, 0.7834365758695939),
 (759, 0.7660914117281696),
 (1198, 0.7660914117281696),
 (2125, 0.7660914117281696),
 (1262, 0.7602564677396255),
 (73, 0.7564590028100435),
 (221, 0.7564590028100435),
 (222, 0.7564590028100435),
 (263, 0.7564590028100435),
 (411, 0.7564590028100435),
 (576, 0.7564590028100435),
 (628, 0.7564590028100435),
 (1139, 0.7564590028100435),
 (1255, 0.7564590028100435),
 (1586, 0.7564590028100435),
 (1627, 0.7564590028100435),
 (3387, 0.7564590028100435),
 (3923, 0.7564590028100435),
 (4084, 0.7564590028100435),
 (4094, 0.7564590028100435),
 (4100, 0.7564590028100435),
 (789, 0.755115467733458),
 (1081, 0.755115467733458),
 (4248, 0.755115467733458),
 (2097, 0.7546850201678258),
 (1, 0.7461881038084348),
 (5, 0.7461881038084348),
 (9, 0.7461881038084348),
 (12, 0.7461881038084348),
 (17, 0.7461881038084348),
 (19, 0.7461881038084348),
 (20, 0.7461881038084348),
 (30, 0.7461881038084348),
 (38, 0.7461881038084348),
 (70, 0.7461881038084348),
 (96, 0.7461881038084348),
 (105, 0.7461881038084348),
 (124, 0.7461881038084348),
 (127, 0.7461881038084348),
 (197, 0.7461881038084348),
 (204, 0.7461881038084348),
 (206, 0.7461881038084348),
 (259, 0.7461881038084348),
 (312, 0.7461881038084348),
 (325, 0.7461881038084348),
 (326, 0.7461881038084348),
 (375, 0.7461881038084348),
 (480, 0.7461881038084348),
 (706, 0.7461881038084348),
 (737, 0.7461881038084348),
 (826, 0.7461881038084348),
 (1419, 0.7461881038084348),
 (2302, 0.7461881038084348),
 (2348, 0.7461881038084348),
 (2448, 0.7461881038084348),
 (2609, 0.7461881038084348),
 (94, 0.7446352589859611),
 (267, 0.7446352589859611),
 (359, 0.7446352589859611),
 (2333, 0.7446352589859611),
 (3490, 0.7446352589859611),
 (4236, 0.7446352589859611),
 (367, 0.736985505569561),
 (961, 0.736985505569561),
 (303, 0.7327175432616259),
 (1202, 0.7327175432616259),
 (1327, 0.7327175432616259),
 (2932, 0.7327175432616259),
 (3950, 0.7327175432616259),
 (226, 0.7325866237304618),
 (1475, 0.7297608124866227),
 (3474, 0.7297608124866227),
 (1223, 0.7281463676338524),
 (3842, 0.7281463676338524),
 (4229, 0.7281463676338524),
 (2014, 0.7261621204667842),
 (302, 0.7231770119130426),
 (966, 0.7231770119130426),
 (1956, 0.7231770119130426),
 (1032, 0.7226092725116631),
 (1141, 0.7226092725116631),
 (1801, 0.7226092725116631),
 (409, 0.7210920970600688),
 (804, 0.7210920970600688),
 (1005, 0.7210920970600688),
 (1547, 0.7210920970600688),
 (183, 0.7175379075672442),
 (198, 0.7175379075672442),
 (246, 0.7175379075672442),
 (163, 0.7164858259730101),
 (254, 0.7164858259730101),
 (1270, 0.7164858259730101),
 (647, 0.7129262072989797),
 (1846, 0.7129262072989797),
 (909, 0.7102660529547149),
 (911, 0.7102660529547149),
 (83, 0.7057519726317154),
 (775, 0.7057519726317154),
 (3771, 0.7057519726317154),
 (18, 0.7042907626913639),
 (308, 0.7042907626913639),
 (315, 0.7042907626913639),
 (358, 0.7042907626913639),
 (1409, 0.7042907626913639),
 (2123, 0.7042907626913639),
 (2732, 0.7042907626913639),
 (3122, 0.7042907626913639),
 (4305, 0.7042907626913639),
 (4352, 0.7042907626913639),
 (4518, 0.7042907626913639),
 (4617, 0.7036187978568171),
 (2710, 0.7006812338914168),
 (4156, 0.6972475387551023),
 (1948, 0.6954601500422346),
 (2800, 0.6954601500422346),
 (95, 0.6938747226326046),
 (601, 0.6938747226326046),
 (723, 0.6938747226326046),
 (238, 0.6934494950898689),
 (1892, 0.6934494950898689),
 (43, 0.6888119047171325),
 (92, 0.6888119047171325),
 (276, 0.6888119047171325),
 (362, 0.6888119047171325),
 (445, 0.6888119047171325),
 (470, 0.6888119047171325),
 (481, 0.6888119047171325),
 (595, 0.6888119047171325),
 (651, 0.6888119047171325),
 (709, 0.6888119047171325),
 (983, 0.6888119047171325),
 (991, 0.6888119047171325),
 (1257, 0.6888119047171325),
 (1302, 0.6888119047171325),
 (1380, 0.6888119047171325),
 (1393, 0.6888119047171325),
 (1471, 0.6888119047171325),
 (1546, 0.6888119047171325),
 (1610, 0.6888119047171325),
 (1800, 0.6888119047171325),
 (1966, 0.6888119047171325),
 (2015, 0.6888119047171325),
 (2165, 0.6888119047171325),
 (2219, 0.6888119047171325),
 (2279, 0.6888119047171325),
 (2444, 0.6888119047171325),
 (2595, 0.6888119047171325),
 (2816, 0.6888119047171325),
 (3367, 0.6888119047171325),
 (1888, 0.685759455879223),
 (3905, 0.6825611965331091),
 (2223, 0.682229556451941),
 (213, 0.6778562796071878),
 (328, 0.6778562796071878),
 (365, 0.6778562796071878),
 (1251, 0.6778562796071878),
 (1449, 0.6718720907305703),
 (4564, 0.6702319797905711),
 (457, 0.6697911949672056),
 (949, 0.6697911949672056),
 (2707, 0.6697911949672056),
 (63, 0.6657351678669022),
 (369, 0.6657351678669022),
 (418, 0.6657351678669022),
 (543, 0.6657351678669022),
 (1396, 0.6657351678669022),
 (1532, 0.6657351678669022),
 (2844, 0.6657351678669022),
 (2876, 0.6657351678669022),
 (2965, 0.6657351678669022),
 (3150, 0.6657351678669022),
 (3868, 0.6657351678669022),
 (4159, 0.6657351678669022),
 (4180, 0.6657351678669022),
 (4634, 0.6657351678669022),
 (2947, 0.6651543472675657),
 (101, 0.6606378964917216),
 (50, 0.6599030515783392),
 (81, 0.6582247264216019),
 (220, 0.6582247264216019),
 (331, 0.6582247264216019),
 (372, 0.6582247264216019),
 (504, 0.6582247264216019),
 (840, 0.6582247264216019),
 (918, 0.6582247264216019),
 (3590, 0.6582247264216019),
 (4627, 0.6582247264216019),
 (997, 0.6573173359121905),
 (22, 0.6540411126738399),
 (23, 0.6540411126738399),
 (327, 0.6540411126738399),
 (3695, 0.6540411126738399),
 (2533, 0.6539512879826446),
 (1340, 0.6515800722511056),
 (726, 0.6487316254296273),
 (4329, 0.6487316254296273),
 (218, 0.6473151764032059),
 (1349, 0.6473151764032059),
 (2907, 0.6473151764032059),
 (3812, 0.6473151764032059),
 (533, 0.6459531244916336),
 (650, 0.6409447980821701),
 (731, 0.6409447980821701),
 (828, 0.6409447980821701),
 (945, 0.6409447980821701),
 (1058, 0.6409447980821701),
 (1358, 0.6409447980821701),
 (1376, 0.6409447980821701),
 (1709, 0.6409447980821701),
 (3900, 0.6409447980821701),
 (4231, 0.6409447980821701),
 (223, 0.6405013277794869),
 (467, 0.6375900715887174),
 (769, 0.6372632669284753),
 (1056, 0.6372632669284753),
 (1138, 0.6372632669284753),
 (1151, 0.6372632669284753),
 (2247, 0.6372632669284753),
 (69, 0.6306349482370464),
 (1913, 0.6297849316096167),
 (136, 0.629340588081369),
 (289, 0.629340588081369),
 (462, 0.629340588081369),
 (1768, 0.6272011846844476),
 (113, 0.6214717464130821),
 (157, 0.6214717464130821),
 (424, 0.6214717464130821),
 (661, 0.6214717464130821),
 (1341, 0.6214717464130821),
 (2068, 0.6214717464130821),
 (3529, 0.6214717464130821),
 (4549, 0.6214717464130821),
 (298, 0.6213190840290798),
 (1004, 0.6213190840290798),
 (1838, 0.6213190840290798),
 (2055, 0.6213190840290798),
 (2594, 0.6213190840290798),
 (2704, 0.6213190840290798),
 (3093, 0.6213190840290798),
 (3546, 0.6213190840290798),
 (4283, 0.6213190840290798),
 (4302, 0.6213190840290798),
 (4546, 0.6213190840290798),
 (4583, 0.6213190840290798),
 (4594, 0.6213190840290798),
 (3535, 0.6190899003894562),
 (161, 0.6179479437974634),
 (438, 0.6114677353971785),
 (1496, 0.6114677353971785),
 (1602, 0.6114677353971785),
 (1689, 0.6114677353971785),
 (79, 0.6089898708504605),
 (577, 0.6089898708504605),
 (4460, 0.6082775660206099),
 (371, 0.6081469493683327),
 (1983, 0.6081469493683327),
 (2440, 0.6081469493683327),
 (2561, 0.6081469493683327),
 (3457, 0.6081469493683327),
 (3899, 0.6081469493683327),
 (4065, 0.6081469493683327),
 (182, 0.5988650061034313),
 (1017, 0.5988650061034313),
 (1462, 0.5982217417896905),
 (2052, 0.5982217417896905),
 (2361, 0.5982217417896905),
 (3072, 0.5982217417896905),
 (3096, 0.5982217417896905),
 (3293, 0.5982217417896905),
 (3667, 0.5982217417896905),
 (3833, 0.5982217417896905),
 (119, 0.5967224634900683),
 (129, 0.5967224634900683),
 (240, 0.5967224634900683),
 (399, 0.5967224634900683),
 (848, 0.5967224634900683),
 (1661, 0.5967224634900683),
 (2037, 0.5967224634900683),
 (1383, 0.5956884080427785),
 (2945, 0.5956884080427785),
 (4476, 0.5956884080427785),
 (2347, 0.5947148694244411),
 (4386, 0.5923621524058461),
 (496, 0.5916650212462033),
 (714, 0.5916650212462033),
 (1260, 0.5916650212462033),
 (1876, 0.5916650212462033),
 (2608, 0.5916650212462033),
 (2695, 0.5916650212462033),
 (2766, 0.5916650212462033),
 (2813, 0.5916650212462033),
 (3355, 0.5916650212462033),
 (3915, 0.5916650212462033),
 (4651, 0.5916650212462033),
 (4680, 0.5916650212462033),
 (773, 0.5829104974557373),
 (4171, 0.5817112042101342),
 (272, 0.5793947164915025),
 (1446, 0.5793947164915025),
 (3261, 0.5790809780536914),
 (86, 0.5786703757351834),
 (45, 0.5778561548342801),
 (114, 0.5778561548342801),
 (536, 0.5778561548342801),
 (3713, 0.5778561548342801),
 (80, 0.5749424766328737),
 (531, 0.5745682233480152),
 (2811, 0.573730560764931),
 (2741, 0.5729711467176044),
 (1731, 0.5714011716082255),
 (474, 0.5666072506901773),
 (535, 0.5666072506901773),
 (66, 0.5618642206743563),
 (354, 0.5618642206743563),
 (345, 0.5610544571110924),
 (146, 0.5609056539584171),
 (883, 0.5609056539584171),
 (236, 0.559829888719476),
 (450, 0.559829888719476),
 (539, 0.559829888719476),
 (711, 0.559829888719476),
 (1098, 0.559829888719476),
 (1453, 0.559829888719476),
 (1699, 0.559829888719476),
 (2592, 0.559829888719476),
 (2678, 0.559829888719476),
 (2773, 0.559829888719476),
 (3478, 0.559829888719476),
 (3943, 0.559829888719476),
 (4440, 0.559829888719476),
 (4588, 0.559829888719476),
 (4657, 0.559829888719476),
 (4687, 0.559829888719476),
 (158, 0.5572724880470459),
 (537, 0.5572724880470459),
 (621, 0.5555445628951303),
 (21, 0.5473540571450023),
 (53, 0.5473540571450023),
 (61, 0.5473540571450023),
 (74, 0.5473540571450023),
 (301, 0.5473540571450023),
 (336, 0.5473540571450023),
 (464, 0.5473540571450023),
 (604, 0.5473540571450023),
 (633, 0.5473540571450023),
 (995, 0.5473540571450023),
 (1077, 0.5473540571450023),
 (1672, 0.5473540571450023),
 (2053, 0.5473540571450023),
 (3643, 0.5473540571450023),
 (4220, 0.5473540571450023),
 (3304, 0.5454449777780845),
 (541, 0.543959308630883),
 (795, 0.543959308630883),
 (921, 0.543959308630883),
 (1273, 0.543959308630883),
 (1997, 0.543959308630883),
 (1968, 0.5439159046487869),
 (2120, 0.5439159046487869),
 (2586, 0.5439159046487869),
 (4331, 0.5439159046487869),
 (2345, 0.5422486186168713),
 (2649, 0.5422486186168713),
 (2790, 0.5422486186168713),
 (3085, 0.5422486186168713),
 (3654, 0.5422486186168713),
 (3799, 0.5422486186168713),
 (4040, 0.5422486186168713),
 (4188, 0.5422486186168713),
 (4365, 0.5422486186168713),
 (4415, 0.5422486186168713),
 (4638, 0.5422486186168713),
 (745, 0.5422452774499107),
 (1183, 0.5422452774499107),
 (2546, 0.5422452774499107),
 (4497, 0.5418010634389385),
 (2338, 0.536451779439972),
 (3983, 0.5350131223715233),
 (667, 0.5331982948420113),
 (170, 0.5311851888529373),
 (606, 0.5311851888529373),
 (887, 0.5311851888529373),
 (1320, 0.5311851888529373),
 (2143, 0.5311851888529373),
 (8, 0.5290709893371626),
 (15, 0.5290709893371626),
 (32, 0.5290709893371626),
 (37, 0.5290709893371626),
 (62, 0.5290709893371626),
 (107, 0.5290709893371626),
 (112, 0.5290709893371626),
 (141, 0.5290709893371626),
 (173, 0.5290709893371626),
 (189, 0.5290709893371626),
 (195, 0.5290709893371626),
 (273, 0.5290709893371626),
 (332, 0.5290709893371626),
 (337, 0.5290709893371626),
 (364, 0.5290709893371626),
 (772, 0.5290709893371626),
 (1062, 0.5290709893371626),
 (1305, 0.5290709893371626),
 (1738, 0.5290709893371626),
 (1970, 0.5290709893371626),
 (2954, 0.5290709893371626),
 (3898, 0.5290709893371626),
 (2228, 0.5289668435290454),
 (889, 0.5236877427036774),
 (666, 0.5235031663394644),
 (2283, 0.5235031663394644),
 (185, 0.5223288610385075),
 (3814, 0.5223288610385075),
 (1256, 0.5223138355524113),
 (1736, 0.5192710140587887),
 (2825, 0.5174271718817091),
 (194, 0.5139447125043662),
 (988, 0.5111292738614082),
 (2996, 0.5111292738614082),
 (4369, 0.5111292738614082),
 (208, 0.5107371933333631),
 (296, 0.5107371933333631),
 (2467, 0.5097449413304264),
 (3101, 0.5097449413304264),
 (3552, 0.5097449413304264),
 (4621, 0.5097449413304264),
 (446, 0.509373087283145),
 (1041, 0.509373087283145),
 (2368, 0.509373087283145),
 (2698, 0.509373087283145),
 (2865, 0.509373087283145),
 (3817, 0.509373087283145),
 (103, 0.5071491125814311),
 (159, 0.5071491125814311),
 (578, 0.5071491125814311),
 (793, 0.5071491125814311),
 (2325, 0.5071491125814311),
 (3693, 0.5071491125814311),
 (1635, 0.5065835446635645),
 (77, 0.5043585118731458),
 (1735, 0.5043585118731458),
 (1130, 0.5019519357258211),
 (1125, 0.5017705598363021),
 (3255, 0.5012266797130461),
 (3933, 0.5010648416503346),
 (766, 0.4999210550431027),
 (1360, 0.4999210550431027),
 (1619, 0.4999210550431027),
 (2044, 0.4999210550431027),
 (2517, 0.4999210550431027),
 (2703, 0.4999210550431027),
 (2780, 0.4999210550431027),
 (2905, 0.4999210550431027),
 (2943, 0.4999210550431027),
 (2955, 0.4999210550431027),
 (3175, 0.4999210550431027),
 (3526, 0.4999210550431027),
 (3574, 0.4999210550431027),
 (3578, 0.4999210550431027),
 (3808, 0.4999210550431027),
 (3860, 0.4999210550431027),
 (3979, 0.4999210550431027),
 (4483, 0.4999210550431027),
 (361, 0.49735012231765807),
 (3013, 0.49735012231765807),
 (3564, 0.49735012231765807),
 (4608, 0.49735012231765807),
 (3296, 0.49709469217061886),
 (115, 0.4967245172277753),
 (193, 0.4967245172277753),
 (306, 0.4967245172277753),
 (566, 0.4967245172277753),
 (1121, 0.4967245172277753),
 (1314, 0.4967245172277753),
 (1708, 0.4967245172277753),
 (3088, 0.49651424351343765),
 (3139, 0.49651424351343765),
 (24, 0.49574097409800466),
 (155, 0.49574097409800466),
 (214, 0.49574097409800466),
 (234, 0.49574097409800466),
 (271, 0.49574097409800466),
 (379, 0.49574097409800466),
 (469, 0.49574097409800466),
 (1224, 0.49574097409800466),
 (1282, 0.49574097409800466),
 (1361, 0.49574097409800466),
 (2464, 0.49574097409800466),
 (2599, 0.49574097409800466),
 (3159, 0.49574097409800466),
 (3166, 0.49574097409800466),
 (3446, 0.49574097409800466),
 (4052, 0.49574097409800466),
 (4055, 0.49574097409800466),
 (4398, 0.49574097409800466),
 (4495, 0.49574097409800466),
 (4515, 0.49574097409800466),
 (591, 0.494078407577436),
 (618, 0.494078407577436),
 (926, 0.494078407577436),
 (1682, 0.494078407577436),
 (48, 0.49363263928743273),
 (377, 0.49363263928743273),
 (1434, 0.49363263928743273),
 (1513, 0.49172525188308386),
 (743, 0.48863306549339003),
 (4350, 0.48863306549339003),
 (4130, 0.48511769731704296),
 (495, 0.48393402267419394),
 (620, 0.48174414481429734),
 (897, 0.48174414481429734),
 (1486, 0.48174414481429734),
 (1782, 0.48174414481429734),
 (2442, 0.48174414481429734),
 (2843, 0.48174414481429734),
 (2959, 0.48174414481429734),
 (3140, 0.48174414481429734),
 (3649, 0.48174414481429734),
 (4452, 0.48174414481429734),
 (4534, 0.48174414481429734),
 (217, 0.4812780025008105),
 (260, 0.4812780025008105),
 (407, 0.4812780025008105),
 (525, 0.4812780025008105),
 (657, 0.4812780025008105),
 (682, 0.4812780025008105),
 (778, 0.4812780025008105),
 (821, 0.4812780025008105),
 (877, 0.4812780025008105),
 (1001, 0.4812780025008105),
 (1065, 0.4812780025008105),
 (1241, 0.4812780025008105),
 (1695, 0.4812780025008105),
 (1764, 0.4812780025008105),
 (1825, 0.4812780025008105),
 (1828, 0.4812780025008105),
 (2090, 0.4812780025008105),
 (2636, 0.4812780025008105),
 (2761, 0.4812780025008105),
 (2942, 0.4812780025008105),
 (2992, 0.4812780025008105),
 (4219, 0.4812780025008105),
 (626, 0.4802707713051576),
 (1631, 0.4802707713051576),
 (1760, 0.4802707713051576),
 (2794, 0.4802707713051576),
 (1795, 0.4779747684686463),
 (479, 0.4761044661011189),
 (585, 0.47563837363964906),
 (196, 0.4754944137609941),
 (3471, 0.4741086081521829),
 (1796, 0.4692666018044442),
 (4327, 0.46673392665205266),
 (989, 0.4650383729094923),
 (4037, 0.4643256656303456),
 (329, 0.4640869100697549),
 (558, 0.4640869100697549),
 (1403, 0.4640869100697549),

#### Printing the name of similar movies based on the index

In [19]:
print('Movies suggested for you : \n')
i = 1
for movie in sorted_similar_movies : 
    index = movie[0]
    title_from_index = df[df.index==index]['title'].values[0]
    if (i<=10):
        print(i,'.',title_from_index)
    i+=1

Movies suggested for you :

1 . Avatar
2 . Superman Returns
3 . Man of Steel
4 . X-Men: Days of Future Past
5 . Jupiter Ascending
6 . The Wolverine
7 . Superman
8 . Superman II
9 . Beastmaster 2: Through the Portal of Time
10 . Teenage Mutant Ninja Turtles